### ISSUE TITLE
Applying ema to wavenet

### ISSUE THREAD

**Issue by Hyeokreal** [dhgrs/chainer-VQ-VAE#9]
Hi : ) Thanks for the wonderful code.

I've checked your code that you applied ema to weights in wavenet decoder.
In the paper, they used ema to only embedding spaces.
I'm curious about the intent of applying ema to WaveNet.

Hyukryul YANG

**Comment by dhgrs** [comment]
Hi,

Yes, I apply EMA to only WaveNet. Because I implemented followed by the paper v1.
https://arxiv.org/abs/1711.00937v1
EMA is not mentioned in v1. So I didn't apply it to VQ layer.

And this tweet is why I apply it to WaveNet.
https://twitter.com/heiga_zen/status/980371620127694848
Sorry in Japanese. Dr. Zen who is one of the original WaveNet's author said that they apply EMA to WaveNet.
